// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC1KjgxEorNu9cqYfr08_rRuVT4qgmxZdQ',
    appId: '1:279435314023:web:878553e95ceeed353965c2',
    messagingSenderId: '279435314023',
    projectId: 'healthystyle-aba68',
    authDomain: 'healthystyle-aba68.firebaseapp.com',
    databaseURL: 'https://healthystyle-aba68-default-rtdb.firebaseio.com',
    storageBucket: 'healthystyle-aba68.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD8sO_TdMuYPHiHd1Gc4qIc6Ofx3NdMB-U',
    appId: '1:279435314023:android:07bbfdb374ad1ddf3965c2',
    messagingSenderId: '279435314023',
    projectId: 'healthystyle-aba68',
    databaseURL: 'https://healthystyle-aba68-default-rtdb.firebaseio.com',
    storageBucket: 'healthystyle-aba68.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBta0QeTIOKPWO41m3Ll4yjID71w9uJqRc',
    appId: '1:279435314023:ios:423ebcdc2ff11bd93965c2',
    messagingSenderId: '279435314023',
    projectId: 'healthystyle-aba68',
    databaseURL: 'https://healthystyle-aba68-default-rtdb.firebaseio.com',
    storageBucket: 'healthystyle-aba68.appspot.com',
    iosClientId: '279435314023-9j3pg3n3drh7sm7ftmluvvsv1lq0ordo.apps.googleusercontent.com',
    iosBundleId: 'com.example.bestFlutterUiTemplates',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBta0QeTIOKPWO41m3Ll4yjID71w9uJqRc',
    appId: '1:279435314023:ios:423ebcdc2ff11bd93965c2',
    messagingSenderId: '279435314023',
    projectId: 'healthystyle-aba68',
    databaseURL: 'https://healthystyle-aba68-default-rtdb.firebaseio.com',
    storageBucket: 'healthystyle-aba68.appspot.com',
    iosClientId: '279435314023-9j3pg3n3drh7sm7ftmluvvsv1lq0ordo.apps.googleusercontent.com',
    iosBundleId: 'com.example.bestFlutterUiTemplates',
  );
}
